### ISSUE TITLE
Add optional name_id to new actors

### ISSUE THREAD

**Issue by nickbabcock** [nickbabcock/boxcars#10]
When decoding a new actor, the [extracted `name_id`](https://github.com/nickbabcock/boxcars/blob/master/src/parsing.rs#L442-L447) is unused. The `NewActor` struct should take it in as a field.

**Comment by tfausak** [comment]
I don't understand the importance of names in the replays, but the `name_id` should be an index into the list of names earlier in the replay. For example, Rattletrap looks up the name by index and throws and error if it can't find it. https://github.com/tfausak/rattletrap/blob/2bb84475f0d70ebf659ca4b569bade318d66c916/library/Rattletrap/Decode/SpawnedReplication.hs#L29-L32
