### ISSUE TITLE
Support for RL1.76 replays

### ISSUE THREAD

**Issue by Bakkes** [nickbabcock/boxcars#104]
Just letting you know that the new RL 1.76 update came with some new classes/properties for the heatseeker mode.

Commit with changes needed for my replay parser: https://github.com/Bakkes/CPPRP/commit/16f248e0619cb058d9512d06c65e6cc770b57b67

Based on summary given by CantFly in the ballchasing discord here: https://discordapp.com/channels/577096078843707392/577564876000460821/700580447750717531

Attached 2 replays from new gamemode [heatseekerreplays.zip](https://github.com/nickbabcock/boxcars/files/4493484/heatseekerreplays.zip)

**Comment by nickbabcock** [comment]
Wow much appreciated, thanks! 🙇
