### ISSUE TITLE
Error decoding frame: attribute decoding error encountered: Unrecognized remote id of 11 for actor id / actor object id / attribute id: 21 / 230 / 34

### ISSUE THREAD

**Issue by Sciguymjm** [nickbabcock/boxcars#110]
`
Error decoding frame: attribute decoding error encountered: Unrecognized remote id of 11 for actor id / actor object id / attribute id: 21 / 230 / 34. found attribute ProjectX.GRI_X:Reservations (Reservation) on GameInfo_Soccar.GameInfo.GameInfo_Soccar:GameReplicationInfoArchetype in network cache data. searching all attributes with the same stream id, unknown attributes: [Engine.Pawn:bSimulateGravity, TAGame.CameraSettingsActor_TA:ServerSetUsingSecondaryCamera, TAGame.GameEvent_Team_TA:bDisableMutingOtherTeam], all attributes with that stream id: [(Archetypes.Ball.Ball_Default: Engine.Pawn:bSimulateGravity), (Archetypes.Car.Car_Default: Engine.Pawn:bSimulateGravity), (Archetypes.GameEvent.GameEvent_Soccar: TAGame.GameEvent_Team_TA:bDisableMutingOtherTeam), (Engine.Pawn: Engine.Pawn:bSimulateGravity), (Engine.PlayerReplicationInfo: Engine.PlayerReplicationInfo:PlayerName), (GameInfo_Soccar.GameInfo.GameInfo_Soccar:GameReplicationInfoArchetype: ProjectX.GRI_X:Reservations), (ProjectX.GRI_X: ProjectX.GRI_X:Reservations), (ProjectX.PRI_X: Engine.PlayerReplicationInfo:PlayerName), (ProjectX.Pawn_X: Engine.Pawn:bSimulateGravity), (TAGame.Ball_TA: Engine.Pawn:bSimulateGravity), (TAGame.CameraSettingsActor_TA: TAGame.CameraSettingsActor_TA:ServerSetUsingSecondaryCamera), (TAGame.Car_TA: Engine.Pawn:bSimulateGravity), (TAGame.Default__CameraSettingsActor_TA: TAGame.CameraSettingsActor_TA:ServerSetUsingSecondaryCamera), (TAGame.Default__PRI_TA: Engine.PlayerReplicationInfo:PlayerName), (TAGame.GRI_TA: ProjectX.GRI_X:Reservations), (TAGame.GameEvent_Soccar_TA: TAGame.GameEvent_Team_TA:bDisableMutingOtherTeam), (TAGame.GameEvent_Team_TA: TAGame.GameEvent_Team_TA:bDisableMutingOtherTeam), (TAGame.PRI_TA: Engine.PlayerReplicationInfo:PlayerName), (TAGame.RBActor_TA: Engine.Pawn:bSimulateGravity), (TAGame.Vehicle_TA: Engine.Pawn:bSimulateGravity)].  Context: on frame: 0, last updated actor: (actor stream id / object id / name: 21 / 230 / GameInfo_Soccar.GameInfo.GameInfo_Soccar:GameReplicationInfoArchetype, attribute stream id / object id / name: 34 / 224 / ProjectX.GRI_X:Reservations, attribute: Reservation(Reservation { number: 4, unique_id: UniqueId { system_id: 1, remote_id: Steam(76561198408617501), local_id: 0 }, name: Some("Twitch - AvocadoZLive"), unknown1: true, unknown2: true, unknown3: Some(0) }))
`
[6bacc4c0-5c98-4653-be7b-804ed422ce7f.zip](https://github.com/nickbabcock/boxcars/files/5280113/6bacc4c0-5c98-4653-be7b-804ed422ce7f.zip)

**Comment by tfausak** [comment]
Probably a new remote ID for Epic. 

https://github.com/nickbabcock/boxcars/blob/6c185dd6ff9bd1a1eaf6adcbc1f2c6ea0f6261c0/src/network/attributes.rs#L1231-L1235

**Comment by nickbabcock** [comment]
@tfausak agreed.

I'm in the middle of a move right now, and so it may take me a few days to implement the new epic IDs

**Comment by tfausak** [comment]
This might come in handy :) https://github.com/jjbott/RocketLeagueReplayParser/commit/39de56ca991f799fdbf72c6b045c62c2db2555fa

**Comment by Sciguymjm** [comment]
https://github.com/Bakkes/CPPRP/commit/de6df55b9ccaf07998bb01d52af759829ec8b137#diff-fa322d058e598f9874fd55ab46b06e32L513
