### ISSUE TITLE
PlayerStats Platform returning unexpected result

### ISSUE THREAD

**Issue by bwpikaard** [nickbabcock/boxcars#126]
I tested on your Rocket League Replay Parser test site and a WebAssembly compiled version of boxcars and found that Platform is always returning 0. When parsing the replay myself in Node, I'm getting values of `OnlinePlatform_Steam` or `OnlinePlatform_Epic`, but with boxcars I get `0`. 

My parser:
![image](https://user-images.githubusercontent.com/19532144/127604020-cc5857fe-e9b2-406a-8a8c-c26cbece3db5.png)

Boxcars Output:
![image](https://user-images.githubusercontent.com/19532144/127603898-fd2d882a-80dc-49db-aa16-03856c6a1026.png)

**Comment by tfausak** [comment]
Can you upload the replay that you're testing with?

**Comment by nickbabcock** [comment]
Yes this is an oversight that #127 will fix. Thank you for the report!
