### ISSUE TITLE
Demo Stats

### ISSUE THREAD

**Issue by bwpikaard** [nickbabcock/boxcars#129]
Rocket League seemed to have updated something relating to demos and they no longer appear in the JSON output after parsing a replay. Demos (pre-season 4) were under the actor "TAGame.Car_TA:ReplicatedDemolish", but since season 4, they no longer appear, even if there are demos in the game. Ballchasing had an issue with demos always being 0 and fixed the problem, but no one seems to be aware of what the problem was.

**Comment by bwpikaard** [comment]
Example replay: https://ballchasing.com/replay/a8c65f1e-8aff-43ad-ac52-b9f5c0643412

**Comment by nickbabcock** [comment]
Seems like this has been resolved by looking at a `ReplicatedDemolishGoalExplosion` instead of `ReplicatedDemolish`. Let me know if this should be reopened.
