### ISSUE TITLE
New Rocket League update breaks boxcars

### ISSUE THREAD

**Issue by Zirpoo** [nickbabcock/boxcars#136]
OS: Windows 10
Command used: `rrrocket.exe -n "C3FF7EE89CA5A5A5F04C443B2A57D0F0.replay"`
Command error: `An error occurred: Unable to parse replay`
Caused by:
`
0: Error decoding frame: attribute unknown 
or not implemented: actor id / actor object id 
/ attribute id: 5 / 153 / 31. found attribute ProjectX.GRI_X:MatchGuid (unknown to boxcars) on GameInfo_Basketball.GameInfo.GameInfo_Basketball:GameReplicationInfoArchetype in network cache data. This is likely due to a rocket league update or an atypical replay. File a bug report! Context: on frame: 0, last updated actor: (actor stream id / object id / name: 5 / 153 / GameInfo_Basketball.GameInfo.GameInfo_Basketball:GameReplicationInfoArchetype, attribute stream id / object id / name: 21 / 133 / Engine.GameReplicationInfo:ServerName, attribute: String("USE4919862026241070452"))
    1: Error decoding frame: attribute unknown 
or not implemented: actor id / actor object id 
/ attribute id: 5 / 153 / 31. found attribute ProjectX.GRI_X:MatchGuid (unknown to boxcars) on GameInfo_Basketball.GameInfo.GameInfo_Basketball:GameReplicationInfoArchetype in network cache data. This is likely due to a rocket league update or an atypical replay. File a bug report! Context: on frame: 0, last updated actor: (actor stream id / object id / name: 5 / 153 / GameInfo_Basketball.GameInfo.GameInfo_Basketball:GameReplicationInfoArchetype, attribute stream id / object id / name: 21 / 133 / Engine.GameReplicationInfo:ServerName, attribute: String("USE4919862026241070452"))
    2: attribute unknown or not implemented: actor id / actor object id / attribute id: 5 / 153 / 31
`

If you need more informations just tell me :)
Hope this is usefull

**Comment by nickbabcock** [comment]
Thanks for the report, can you upload the save here?

**Comment by Zirpoo** [comment]
I deleted this replay but I have another one with similar problems

Caused by:
    0: Error decoding frame: attribute unknown or not implemetor object id / attribute id: 5 / 153 / 31. found attribute PGuid (unknown to boxcars) on GameInfo_Basketball.GameInfo.GammeReplicationInfoArchetype in network cache data. This is lik league update or an atypical replay. File a bug report! Contast updated actor: (actor stream id / object id / name: 5 / 1tball.GameInfo.GameInfo_Basketball:GameReplicationInfoArchetym id / object id / name: 21 / 133 / Engine.GameReplicationInfbute: String("USE8262028140128373005"))
    1: Error decoding frame: attribute unknown or not implemetor object id / attribute id: 5 / 153 / 31. found attribute PGuid (unknown to boxcars) on GameInfo_Basketball.GameInfo.GammeReplicationInfoArchetype in network cache data. This is lik league update or an atypical replay. File a bug report! Contast updated actor: (actor stream id / object id / name: 5 / 1tball.GameInfo.GameInfo_Basketball:GameReplicationInfoArchetym id / object id / name: 21 / 133 / Engine.GameReplicationInfbute: String("USE8262028140128373005"))
    2: attribute unknown or not implemented: actor id / actorute id: 5 / 153 / 31
    
It's all related to the new rocket league basketball map update
[4742F83C44F22221759C97857B846044.zip](https://github.com/nickbabcock/boxcars/files/9789502/4742F83C44F22221759C97857B846044.zip)

**Comment by robotman321** [comment]
@nickbabcock FWIW they changed the casing on this line:
https://github.com/nickbabcock/boxcars/blob/dcb8e1e0125f18522f152fffff11259886f3b785/src/data.rs#L142

From MatchGUID to MatchGuid which should be evident in recent replays (post-update)

**Comment by nickbabcock** [comment]
Thank you everyone for your help 🤗
