### ISSUE TITLE
Dropshot mode error

### ISSUE THREAD

**Issue by Zirpoo** [nickbabcock/boxcars#138]
Hi, I just tested the dropshot mode and tried to parse it but it gave me this error
Any ideas ?
[204C425A44122F8D2EEBF4898DFE5381.zip](https://github.com/nickbabcock/boxcars/files/9956381/204C425A44122F8D2EEBF4898DFE5381.zip)
### Using latest version

Caused by:
    0: Error decoding frame: time is out of range: 0.00000000000000000000000000000000028925757.  Context: on frame: 1, backtracking to frame 0, last new actor: (id: 6, nameId: 6, objId: 254, objName: TAGame.Default__PRI_Breakout_TA, initial trajectory: Trajectory { location: None, rotation: None })
    1: Error decoding frame: time is out of range: 0.00000000000000000000000000000000028925757.  Context: on frame: 1, backtracking to frame 0, last new actor: (id: 6, nameId: 6, objId: 254, objName: TAGame.Default__PRI_Breakout_TA, initial trajectory: Trajectory { location: None, rotation: None })
    2: time is out of range: 0.00000000000000000000000000000000028925757

**Comment by nickbabcock** [comment]
Thanks for the report, I have a fix in #139 😄
