### ISSUE TITLE
rrrocket should use stdin / stdout with one file

### ISSUE THREAD

**Issue by nickbabcock** [nickbabcock/boxcars#14]
When I added rayon support to rrrocket, I changed the functionality so that rrrocket is ran over multiple files so that we can see Rust's parallel iterators at work (and see the huge performance boost). rrrocket currently creates a sibling .json file for each replay, but I miss the days when rrrocket would print the json to stdout so I could pipe with `jq`. Maybe there should be a cli option for this, and if more than one file is given, error out.

**Comment by tfausak** [comment]
For what it's worth, I used to have Octane accept multiple files as input. I have long since given up on that. It's easy enough to parse a bunch of replays in parallel with Bash or PowerShell (or Python or Rust or ...). I think optimizing the interface for one file at a time makes sense.

**Comment by nickbabcock** [comment]
Ran some timings:

Process all the files in a single process in parallel:
```
time ./rrrocket *.replay

real    0m0.143s
user    0m0.052s
sys     0m0.124s
```

Process each file in a separate process:
```
time find . -iname "*.replay" -print0 | xargs -0 -P0 -n1 ./rrrocket

real    0m4.420s
user    0m0.000s
sys     0m0.020s
```
So there does seem to be significant startup and teardown costs to a process when there are many files to parse

**Comment by tfausak** [comment]
Huh, weird. I wouldn't think there'd be so much overhead.

**Comment by nickbabcock** [comment]
Yeah process startup and teardown was exasperated as I had all cores pinned at 100% for fuzzing -- but I was surprised as well when I first saw the numbers.

You can see the overhead here (`/bin/echo` is important):

```
time for i in {1..300}; do /bin/echo $i > /dev/null; done

real    0m0.604s
user    0m0.224s
sys     0m0.301s
```

**Comment by tfausak** [comment]
Dang! I knew that starting a process had some overhead, but I didn't expect it to be that much. Seems like it might be worthwhile to have Boxcars/`rrrocket` accept multiple input files. One of the reasons that Rattletrap doesn't do that is because it also generates replays. I don't know if anyone actually uses that feature, but it makes it hard to design a CLI that supports multiple files.

**Comment by nickbabcock** [comment]
I'm not sold on the rrrocket name -- thinking about just calling it boxcars-cli 😉 

But to add to your confusion. The [latest release](https://github.com/nickbabcock/boxcars/releases/tag/v0.1.0) (which is much outdated) takes a single file and outputs JSON, but the [version on master](https://github.com/nickbabcock/boxcars/blob/110a3406ae5fe2b7497c8bac7d98bcb086fac66c/rrrocket/src/main.rs) takes multiple files as arguments and writes each output to a sibling .json file. The version on master uses rayon to parse `n` files at once and sees an almost perfect linear scalability.
