### ISSUE TITLE
ProjectX.GRI_X:MatchGuid (unknown to boxcars) with recent Rocket League replays

### ISSUE THREAD

**Issue by jawnv6** [nickbabcock/boxcars#144]
I don't think this is an issue with carball's invocation.  I'm seeing this error on recent replay files:
Exception: Error decoding frame: attribute unknown or not implemented: actor id / actor object id / attribute id: 13 / 314 / 31. found attribute ProjectX.GRI_X:MatchGuid (unknown to boxcars) on GameInfo_Soccar.GameInfo.GameInfo_Soccar:GameReplicationInfoArchetype in network cache data. This is likely due to a rocket league update or an atypical replay. File a bug report! Context: on frame: 0, last updated actor: (actor stream id / object id / name: 13 / 314 / GameInfo_Soccar.GameInfo.GameInfo_Soccar:GameReplicationInfoArchetype, attribute stream id / object id / name: 21 / 294 / Engine.GameReplicationInfo:ServerName, attribute: String("TNA114-Voxel5"))
[example.zip](https://github.com/nickbabcock/boxcars/files/10409213/example.zip)

**Comment by nickbabcock** [comment]
This looks to be an issue with an outdated boxcars-py carball package, as the attached replay parses fine on the latest version of boxcars. I believe you need to update it yourself, as I'm not a maintainer of that package.

**Comment by jawnv6** [comment]
Thanks!
