### ISSUE TITLE
Possible platform parsing error

### ISSUE THREAD

**Issue by mohkamfer** [nickbabcock/boxcars#146]
https://github.com/nickbabcock/boxcars/blob/1bb628c952666acd63e4ff5eb11b64c67764aebf/src/header.rs#L123

Here you're handling a very abnormal behavior of replay files to delegate the value of a ByteProperty to its key instead. However, I noticed in some replay files (of my own matches, actually) that this issue can also happen with "OnlinePlatform_Epic" and surprisingly "OnlinePlatform_Dingo", and god only knows what "Dingo" platform is :D

Due to the amount of "platform types" that usually get read into the key instead of the value of ByteProperties, I thought to myself why not flip the pattern match, and only read a value if the key was "Platform", but then you're never sure if ByteProperty is only used for this :/

**Comment by mohkamfer** [comment]
Just now, I also found "OnlinePlatform_NNX"

**Comment by mohkamfer** [comment]
https://github.com/TaylorSasser/RLForge/blob/600781c01c59876e17747150fe06dd253daffe2c/RLForge/RLForge/RL/SDK/RL_Engine_structs.hpp#L244-L256

**Comment by nickbabcock** [comment]
I'm not sure what the proposal is here. If there is a replay that fails to parse, please upload.
