### ISSUE TITLE
Anybody know how to get the value of an object?

### ISSUE THREAD

**Issue by i1Fury** [nickbabcock/boxcars#154]
I'm trying to simply list which car the players loaded in with. I know I need to do something with `TAGame.PRI_TA:ClientLoadoutOnline` but I'm fairly new to Rust and am having a lot of difficulties understanding how to interact with this crate.

**Comment by nickbabcock** [comment]
This should get you a start.
```rust
// first convert the desired attribute name into its object id:
let loadout_id = replay
    .objects
    .iter()
    .position(|val| val == "TAGame.PRI_TA:ClientLoadoutOnline")
    .map(|index| boxcars::ObjectId(index as i32))
    .ok_or_else(|| format!("Expected {} to be present in replay", "TAGame.PRI_TA:ClientLoadoutOnline"))?;

// Then we can dive into the replay
let network = replay.network_frames.unwrap();
for frame in network.frames {
    for attr in frame.updated_actors {
        if attr.object_id == loadout_id {
            if let Attribute::LoadoutOnline(loadouts) = attr.attribute {
                // do something with loadouts.
            }
        }
    }
}
```

**Comment by i1Fury** [comment]
this doesn't seem to work :/ when we loop through the attributes in frame.updated_actors, none of the object ids equal the loadout id. i tried it with 3 replay files :[

**Comment by i1Fury** [comment]
[output.txt](https://github.com/nickbabcock/boxcars/files/12348593/output.txt)
Just some context :)
```rs
fn main() -> Result<(), Box<dyn error::Error>> {
    let data = fs::read(REPLAY_PATH)?;

    let replay = ParserBuilder::new(&data[..])
        .on_error_check_crc()
        .ignore_network_data_on_error()
        // .never_parse_network_data()
        .parse()?;

    if let Some(network) = replay.network_frames.as_ref() {
        let loadout_id = replay
                .objects
                .iter()
                .position(|val| val == "TAGame.PRI_TA:ClientLoadoutOnline")
                .map(|index| boxcars::ObjectId(index as i32))
                .ok_or_else(|| format!("Expected {} to be present in replay", "TAGame.PRI_TA:ClientLoadoutOnline"))?;
        
        println!("loadout_id: {:?}", loadout_id.to_string());
        let network = replay.network_frames.unwrap();
        let mut i: i32 = 0;
        for frame in &network.frames {
            for attr in &frame.updated_actors {
                println!("attr: {:?} == {:?}", attr.object_id.to_string(), loadout_id.to_string());
                if attr.object_id.to_string() == loadout_id.to_string() {
                    if let Attribute::LoadoutOnline(loadouts) = &attr.attribute {
                        let mut file = File::create(format!("loadout_{}.txt", &i))?;
                        file.write_all(format!("{:?}", loadouts).as_bytes())?;
                        i += 1;
                        println!("loadouts: {:?}", loadouts);
                    }
                }
            }
        }
    }

    Ok(())
}
```

**Comment by nickbabcock** [comment]
Don't sweat it, if you want a replay that has that attribute you can checkout

```
assets/replays/good/51235.replay
```

But perhaps you are really looking for `TeamLoadout` attribute housed under

```
TAGame.PRI_TA:ClientLoadouts
```

Or the `LoadoutsOnline` attribute under

```
TAGame.PRI_TA:ClientLoadoutsOnline
```

Seems like it has a lot of information you may seek

**Comment by i1Fury** [comment]
I tried all the loadout variations and none of them appeared in the replays I tested. Shouldn't the player's preset be in every single replay, considering when I load it in Rocket League it knows what their preset is?

**Comment by nickbabcock** [comment]
I would be hesitant to make too many assumptions about an ever changing format. I'm seeing loadouts across several saves, so I'm not sure what issue you are running into, but you can play around with it some more.

I used the following code to just print out the loadouts.

```rust
    for frame in network.frames {
        for attr in frame.updated_actors {
            match attr.attribute {
                Attribute::Loadout(loadout) => {
                    println!("{:?}", loadout);
                },
                Attribute::LoadoutOnline(loadout) => {
                    println!("{:?}", loadout);
                }
                Attribute::LoadoutsOnline(loadout) => {
                    println!("{:?}", loadout);
                }
                Attribute::TeamLoadout(loadout) => {
                    println!("{:?}", loadout);
                }
                _ => {}
            }
        }
    }
```

**Comment by i1Fury** [comment]
> I would be hesitant to make too many assumptions about an ever changing format. I'm seeing loadouts across several saves, so I'm not sure what issue you are running into, but you can play around with it some more.
> 
> 
> 
> I used the following code to just print out the loadouts.
> 
> 
> 
> ```rust
> 
>     for frame in network.frames {
> 
>         for attr in frame.updated_actors {
> 
>             match attr.attribute {
> 
>                 Attribute::Loadout(loadout) => {
> 
>                     println!("{:?}", loadout);
> 
>                 },
> 
>                 Attribute::LoadoutOnline(loadout) => {
> 
>                     println!("{:?}", loadout);
> 
>                 }
> 
>                 Attribute::LoadoutsOnline(loadout) => {
> 
>                     println!("{:?}", loadout);
> 
>                 }
> 
>                 Attribute::TeamLoadout(loadout) => {
> 
>                     println!("{:?}", loadout);
> 
>                 }
> 
>                 _ => {}
> 
>             }
> 
>         }
> 
>     }
> 
> ```

This worked! Thank you! I also learned a lot about Rust from this! My only problem is that the docs for a lot of Rust crates are very difficult to piece together. With documentation for other languages, I'd come in with a small task to complete, and be able to click on a very general area that my solution will probably be in. I'd swiftly navigate through the jungle of well-documented objects and functions until I find the combination of tools I needed. With Rust, I can get through 0-2 clicks before there is an absence of description or direction. Do you have any advice for us newbies before we close the thread?

**Comment by nickbabcock** [comment]
For this crate, at least, it's tough as reverse engineering a proprietary format doesn't often leave the confidence to document what everything means. (but I can always do a better job documenting)

Though typically you should be able to find good quality examples on a crate's https://docs.rs/ or in the crate repo there may be an `examples/` folder.
