### ISSUE TITLE
Missing players in results

### ISSUE THREAD

**Issue by netizen01** [nickbabcock/boxcars#157]
Download the replay file from here:
https://ballchasing.com/replay/6fa49901-0840-4685-8f14-ed6548971460#overview

Upload to your web parser or parse locally.

The Player "EvillRage" has 2 goals in this game, and shows up in the "Goals" array, but is missing from the Player Stats area. There are a few bots in here, wondering if that's causing problems.

**Comment by nickbabcock** [comment]
The player stats summarized by Psyonix in a replay are best effort and are not authoritative. 

AFAIK, you're better off looking for these attributes:

```
    "TAGame.PRI_TA:MatchShots",
    "TAGame.PRI_TA:MatchSaves",
    "TAGame.PRI_TA:MatchAssists",
    "TAGame.PRI_TA:MatchGoals",
    "TAGame.PRI_TA:MatchScore",
```

You'll want to find the final frame that contains an attribute for `TAGame.PRI_TA:MatchGoals` (object id 193 in replay), which will contain the goals for each actor id. IIRC, to find the actor name, find the most recent frame for that actor id that uses `Engine.PlayerReplicationInfo:PlayerName` (object id 144 in given replay)

Boxcars is a low level parser. If it is too low level, others have built higher level abstractions on top of boxcars, like [substr-actor](https://github.com/rlrml/subtr-actor)
