### ISSUE TITLE
Notes on decoding header properties

### ISSUE THREAD

**Issue by tfausak** [nickbabcock/boxcars#165]
I recently ported part of Rattletrap to Unison. I called it [Uniball](https://share.unison-lang.org/@tfausak/uniball). While I was porting things over, I discovered some stuff about decoding properties in the header which you might find useful. 

https://github.com/nickbabcock/boxcars/blob/945db74bf6447378f26b8c9535d04389c417e44f/src/header.rs#L106-L118

When decoding a property, there is indeed a size prefix (unsigned 64 bit integer). You can see the details in my [Property.decode](https://share.unison-lang.org/@tfausak/uniball/code/releases/3.0.0/latest/terms/rocketLeague/Property/decode) function, but the key takeaways are:

- If the property is not a bool or byte then the size prefix is used as-is.
- If the property is a bool, then the size is 0 but should be interpreted as 1 for most versions but 4 for version `0.0.null`. 
- If the property is a byte, then the size should be increased by 19 (the length of `OnlinePlatform`) for most versions but not changed for version `0.0.null`. 

That should allow you to scope the property parsers to an expected number of bytes. It will also get rid of a couple special cases. Specifically these two:

https://github.com/nickbabcock/boxcars/blob/945db74bf6447378f26b8c9535d04389c417e44f/src/header.rs#L84
https://github.com/nickbabcock/boxcars/blob/945db74bf6447378f26b8c9535d04389c417e44f/src/header.rs#L123

Both cases involve replays with the special version number `0.0.null`. Psyonix must have screwed up their encoding for that version. 

The first case involves decoding a bool property as the last element. Since they're usually 1 byte but in version `0.0.null` they're 4 bytes, there are an extra 3 bytes to decode. This ends up getting interpreted as part of the "key", so the check against `\0\0\0None` is necessary. (See [Bool.decode](https://share.unison-lang.org/@tfausak/uniball/code/releases/3.0.0/latest/terms/rocketLeague/Bool/decode) for specifics.) 

The second case involves decoding a byte property anywhere. Usually they include the "key" `OnlinePlaform`, but in version `0.0.null` that key is missing. The value is the same, so I think the key is just implied. (See [Byte.decode](https://share.unison-lang.org/@tfausak/uniball/code/releases/3.0.0/latest/terms/rocketLeague/Byte/decode) for specifics.) 

None of this changes any of the results. The current way of doing things works fine, it's just a little hacky behind the scenes. I thought you might be interested to see a different way to handle decoding these values. 

I haven't ported these changes back into Rattletrap yet, which is why I linked to code on Unison Share instead of GitHub.

**Comment by tfausak** [comment]
Oh, also this could go away:

https://github.com/nickbabcock/boxcars/blob/945db74bf6447378f26b8c9535d04389c417e44f/src/core_parser.rs#L103-L109

It's related to the first issue about 4-byte bool properties. My [String.decode](https://share.unison-lang.org/@tfausak/uniball/code/releases/3.0.0/latest/terms/rocketLeague/String/decode) doesn't have this special case for `0x0500_0000` anymore.

**Comment by nickbabcock** [comment]
TIL about Unison. Thank you for the notes, let me sink my teeth into them

**Comment by nickbabcock** [comment]
Nice! Everything worked and I was able to confirm no output changes
