### ISSUE TITLE
Possibly duplicated demolish data

### ISSUE THREAD

**Issue by zcvaters** [nickbabcock/boxcars#176]
I'm seeing it show up twice in some cases.

![image](https://github.com/user-attachments/assets/6537c631-dd19-41dc-b445-dd16419d1f67)
[ranked-with-newman.zip](https://github.com/user-attachments/files/17949564/ranked-with-newman.zip)

**Comment by zcvaters** [comment]
Sequence of events, demolished as I was hitting the ball to the net, the ball went in. Looking at `TAGame.Car_TA:ReplicatedDemolishGoalExplosion` , so it could be my misunderstanding of this attribute.

**Comment by nickbabcock** [comment]
Yeah sounds like if this occurs in the data twice, then boxcars is correctly exposing it.

It's up to a higher level to interpret the data, and do any sort of de-duplication.

**Comment by zcvaters** [comment]
Ok, interesting, I guess it's a little bit tricky to know but if its withing N frames and the attackers/victims are similar. Then that's pretty much it.
