### ISSUE TITLE
Slicing by 8 to speed up crc check

### ISSUE THREAD

**Issue by Bakkes** [nickbabcock/boxcars#58]
Was reading through the source code and saw that you attempted to implement slice-by-8 but didn't manage to get it to work. I've got it working in my parser if you're still interested in implementing it https://github.com/Bakkes/CPPRP/blob/master/CPPRP/CRC.h#L245
I got about a 4x speedup using it when crcing header + network data.

I've tried to implement it in Rust myself and send a PR, but I've never programmed in it before and didn't manage to get very far. Feel free to copy/convert the code or close this issue if it's not something you're interested in anymore, just thought I'd let you know after reading the comments in crc.rs 😛

**Comment by nickbabcock** [comment]
Oh wow, that's amazing. Let me take a look at your implementation and see if I can do the same thing
