### ISSUE TITLE
Even faster CRC check with slice by 16/32

### ISSUE THREAD

**Issue by Bakkes** [nickbabcock/boxcars#63]
Hello again! I've ran some tests for my replay parser to see if the crc check could be sped up even more using slice by 16/32 and some loop unrolling.

It looks like SB8 is faster than SB16 when CRCing up to 20kb (typical replay header size?). SB16 seems to be faster >20kb and even twice as fast at >500kb so probably worth implementing when CRCing the entire replay.

SB16 -> SB32 didn't seem to make much of a difference with GCC and is sometimes even slower, however with clang it is faster (but still not as fast as GCC's SB16/32). I'm not sure what the result would be in the rust compiler.

Test results: https://gist.github.com/Bakkes/e5ad150aa76d63d50c23f9fd76001edd#file-resulsts-txt-L1

Code: https://gist.github.com/Bakkes/e5ad150aa76d63d50c23f9fd76001edd#file-crctest-cpp-L1 (includes table generation at compile time so code doesn't get as cluttered)

Full tables are dumped at the bottom of that gist if you're interested in trying SB16/32 in rust.

**Comment by nickbabcock** [comment]
Oh wow, I tried out the SB32 and saw another 2x improvement (benchmarked against 1MB of data)
