### ISSUE TITLE
Extract PS4 Id

### ISSUE THREAD

**Issue by nickbabcock** [nickbabcock/boxcars#9]
Currently the only logic in place is reading the patch / net version and grabbing 32 or 40 bytes. [Rattletrap contains the logic](https://github.com/tfausak/rattletrap/blob/a31a27fc5f43fee4c5a643ae8381a3765d9c9877/library/Rattletrap/Decode/RemoteId.hs) to decode a string. It would be nice to see a unit test or a description of how the name is encoded.

**Comment by tfausak** [comment]
I'm pretty sure PS4 names are required to be ASCII. The also have a fixed size, which is why Rattletrap strips null bytes from the end.
