### ISSUE TITLE
CamSettings swiftness should be stiffness

### ISSUE THREAD

**Issue by nickbabcock** [nickbabcock/boxcars#91]
https://github.com/nickbabcock/boxcars/blob/03304eaac299f41d0942599607dd6aa38c8bb6bd/src/network/attributes.rs#L109

is labelled as stiffness in [rattletrap](https://github.com/tfausak/rattletrap/blob/ee57a340a6baf0ab099226cb7083a172baa2183c/source/library/Rattletrap/Type/CamSettingsAttribute.hs#L16) and [bakkes](https://github.com/Bakkes/CPPRP/blob/383157e808a10673c85d34339202925d4a91885e/CPPRP/data/NetworkData.h#L98)

**Comment by tfausak** [comment]
For what it's worth I probably stole that name from [jjbott](https://github.com/jjbott/RocketLeagueReplayParser/blob/7cdbbaa4aae17ecb1466f0d0b1dff6117a76deda/RocketLeagueReplayParser/NetworkStream/CameraSettings.cs#L15). I have no idea what it should actually be named.

**Comment by nickbabcock** [comment]
Yeah I figure it's best to at least be consistent in naming across parsers even if I do like the thought of a camera having swiftness :laughing:
