### ISSUE TITLE
Name a few unknown fields

### ISSUE THREAD

**Issue by Longi94** [nickbabcock/boxcars#92]
DamageState:
- u8 - State of the dropshot tile (0 - undamaged, 1 - damaged, 2 - destroyed)
- bit - False when undamaged, True otherwise
- u32 - Player actor id of the player of inflicted the damage
- Vector3f - position of the ball at the time of the damage
- bit - True for the dropshot tile that was hit by the ball (center tile of the damage area)
- bit - unknown, seems to be always 0

AppliedDamage might be just an older version of DamageState, would need further investigation with older dropshot replays

Loadout:
second to last 32 bits (unknown5 in Rattletrap, here it's discarded) is the product id of the player's avatar border.

**Comment by nickbabcock** [comment]
All these changes have been incorporated into 0.8.0. Thank you so much for reporting these.
