### ISSUE TITLE
Some unsigned ints should be signed

### ISSUE THREAD

**Issue by Longi94** [nickbabcock/boxcars#93]
I came accross are some unsigned ints with value 4294967295 (2^32 - 1). It would make more sense for them to be signed with value -1. It would also slightly reduce json string size (for rrrocket).

- [ ] the u32 in FlaggedInt
- [ ] the u32 in StatEvent
- [ ] All actor_id references
  - [ ] instigator_id in Pickup and PickupNew
  - [ ] attacker_actor_id and victim_actor_id in Demolish
  - [ ] etc.

I will update this list if I come accross any more while integrating boxcars with carball

**Comment by nickbabcock** [comment]
Yes, excellent point. I'll go through the corpus of replays I have and update accordingly.

Do you know what the significance is of a -1 actor_id? If we'll be updating the types (and -1 represents the absence of an actor for instance) perhaps there's a better type (like `Option<ActorId>`).

**Comment by Longi94** [comment]
It's something along the lines of "invalid" e.g. the player's team actor id is set to -1 when they leave, Or some attributes are initialized with a -1 until another actor interacts with them. I'm not sure if there would be any difference in meaning if we use None or leave it at -1.

**Comment by nickbabcock** [comment]
Made a bunch of fixes and ran the master branch against many thousands of replays and didn't see another occurrence of 4294967295, so I'm going to close this. Let me know if you come across any more!
